// 📋 EMIT PATCHNOTES.md FROM THE TABLE THE GAME ITSELF SHOWS — 2026-08-28
//
// Thomas: *"that way i can share updates with playtesters on what got changed and added"* — so the
// notes need to be pasteable into a chat, not only readable in the app.
//
// 🔑 GENERATED, NEVER HAND-EDITED. Two copies of a changelog drift exactly the way two copies of
// the arrangement search did, and a changelog that disagrees with the build is worse than none —
// it is the version people quote. `PATCH_NOTES` in game.js is the single source; this is a
// rendering of it, and the file it writes says so at the top.
//
// ⚠️ It also FAILS LOUDLY when the newest entry does not match the current build, because that is
// the one mistake this whole system exists to catch: bumping the cache-buster and shipping a
// release nobody wrote up.
//
//   Usage, from prototype/ :   node dev/notes.js
'use strict';
const fs = require('fs');
const path = require('path');
const H = require('./headless.js');
const B = H.sandbox;

const notes = B.PATCH_NOTES;
if (!notes || !notes.length) { console.error('❌ PATCH_NOTES is empty or unreachable.'); process.exit(1); }

// BUILD is read off the <script src> tag, which the headless DOM stub does not have, so ask
// index.html directly — it is the file that actually decides what a browser runs.
const html = fs.readFileSync(path.join(__dirname, '..', 'index.html'), 'utf8');
const m = html.match(/game\.js\?v=(\d+)/);
const build = m ? m[1] : '?';

// strip the game's markup — the notes carry <b> only, by the same rule every content string does
const md = t => String(t).replace(/<br\s*\/?>/gi, '\n').replace(/<b>/g, '**').replace(/<\/b>/g, '**')
                         .replace(/<[^>]+>/g, '');

const out = [];
out.push('# Emberwick — what\'s new');
out.push('');
out.push('Play: https://iimthomas.github.io/emberwick/play/');
out.push('');
out.push('<!-- GENERATED by `node dev/notes.js` from PATCH_NOTES in game.js. Do not edit by hand:');
out.push('     the game shows the same table, and a changelog that disagrees with the build is the');
out.push('     version people quote. Add the entry in game.js and re-run this. -->');
out.push('');

for (const n of notes) {
  out.push(`## build ${n.build} — ${n.title}`);
  out.push(`*${n.date}*`);
  out.push('');
  if (n.warn) { out.push(`> ⚠️ ${md(n.warn)}`); out.push(''); }
  for (const [label, rows] of [['Added', n.added], ['Changed', n.changed], ['Fixed', n.fixed]]) {
    if (!rows || !rows.length) continue;
    out.push(`**${label}**`);
    for (const r of rows) out.push(`- ${md(r)}`);
    out.push('');
  }
}
out.push('---');
out.push('');
out.push('*History before build 385 is not recorded.*');

const dest = path.join(__dirname, '..', 'PATCHNOTES.md');
fs.writeFileSync(dest, out.join('\n') + '\n', 'utf8');

const newest = String(notes[0].build);
console.log(`\n📋 wrote PATCHNOTES.md — ${notes.length} entries, newest build ${newest}`);
if (newest !== build) {
  console.error(`\n❌ index.html serves game.js?v=${build} but the newest note is build ${newest}.`);
  console.error(`   Add an entry to PATCH_NOTES in game.js before cutting this release.\n`);
  process.exitCode = 1;
} else {
  console.log(`   ✅ matches index.html (game.js?v=${build})\n`);
}
